[phases.setup]
# Use the appropriate version of PHP and install Composer
nixpkgs = ["php", "composer", "nodejs-16_x"]

[phases.build]
# Install PHP dependencies and build the project
commands = [
    "composer install --no-dev --optimize-autoloader",
    "npm install",
    "npm run build"
]

[phases.start]
# Start the PHP server
commands = ["php artisan serve --host=0.0.0.0 --port=3306"]
